### ISSUE TITLE
[Tracker] Things to do in refactoring docs.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/docs#303]
The docs need a makeover. Things to to:

 - [x] Make it a proper Silex app (PR #304)
 - [x] Allow for more levels (PR #304)
 - [x] Update to Foundation 6 (PR #306)
 - [x] Revamp templates (in progress)
 - [x] Overhaul navigation (main menu, toggle between versions)
 - [x] Split content in more, smaller pages (for more pinpointed searching)
 - [x] Integrate cheatsheet into docs (PR #310)
 - [x] Integrate class reference into docs (PR #309)
 - [x] Implement better search (Algolia?)
 - [x] Add Google Analytics tracker

**Comment by bobdenotter** [comment]
Boom! :boom:
