### ISSUE TITLE
Docs restructuring tracker

### ISSUE THREAD

**Issue by SahAssar** [bolt/docs#483]
- [ ] Create screenshots for all fields
- [ ] Add bolt's internal fields (datecreated etc.) to Field Types
- [ ] Update all screenshots in docs/manual to 3.1 (most are 2.0/2.2) (#471)
- [ ] Restructure Templating section (Assinged to Phillipp)

```
- **Templating** completely new structure
    - Intro
    - File Structure
    - Theme Configuration
    - Template Specific Fields
    - Automatic Template Selection
    - Twig
        - Twig Basics
        - Bolt Twig Additions **from "Templating/Bolt template tags", needs rewrite**
    - Content Pages
        - Homepage
        - Listing Pages
        - Record Pages
        - Searchresult Page
    - Pagination
    - Fetching Content via setcontent
    - Using Widgets
    - Other
        - Strict Variables
        - Live Editor
        - Using the Field-tag
```

```
from bolt internals:
dump() Twig tag **move to Bolt's own template tags**
```

---
- [ ] Go over ContentTypes section to make sure it reads well (Assinged to SahAssar)
- [ ] Move "How To Use Bolt extensions" to configuration
- [ ] Create new introduction to bolt extension building in the extend section (What's an extension, what's a bootstrap? When to use what?)
- [ ] Add a full config walkthrough to the configuration section (goal is to be able to remove comments/options for the .dist files)

```
- Configuration
    - Setting up Bolt (**could have better wording for the title**)
    - Database Configuration
    - **Permissions** moved from "Working with Bolt"
    - **Using menus** moved from "Working with Bolt"
    - **Installing and using Extensions** basicly just from "Extending Bolt/Introduction to Bolt Extensions"
    - **..to be continued with all possible config options. Thinking with Gawain and Svante needed**
```

---
- [ ] Add a better page on custom bootstrapping (perhaps ross can help)
- [ ] Perhaps fix some of the absolute links in 2.2 so that they don't 404 to 3.1 docs
- [ ] Hint in `index.twig` dialogue & README that base theme should be moved/copied

**Comment by PhillippOhlandt** [comment]
@rossriley Would you like to make a rewrite of the following page with up-to-date instructions and possible configuration options? https://docs.bolt.cm/3.0/extensions/custom-bootstrapping You seem to know the most about these things.

**Comment by GawainLynch** [comment]
- [ ] Hint in `index.twig` dialogue & README that base theme should be moved/copied

**Comment by PhillippOhlandt** [comment]
To clarify @GawainLynch comment. It is meant for the base-2016 theme inside `bolt/bolt`. What I probably should do is to write a small page about using themes from the marketplace, for the documentation.

**Comment by rossriley** [comment]
@PhillippOhlandt on it.
